### ISSUE TITLE
$pp.$def使用问题

### ISSUE THREAD

**Issue by syusikoku** [CB-ysx/wanandroid-quickapp#9]
this.$app.$def.router.push({uri: uri}),提示push方法找不到，按照你的代码里面的配置在app.ux里面配置了问题还是一样的，所有的 this.$app.$def方式使用都会出现问题，请教一下问题是出现在哪里?

**Comment by charlieysx** [comment]
@syusikoku manifest.json里面有配置router？
`"features": [
...
    { "name": "system.router" }
...
  ]
`

**Comment by syusikoku** [comment]
配置了我把你的那些配置都复制过去了，不光这个报错。取本地数据的那个也会报错

**Comment by charlieysx** [comment]
@syusikoku 方便看一下代码和异常信息？

**Comment by syusikoku** [comment]
this.$app.$def.router.push({ uri: uri })

错误信息:
undefined:2899: TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
    at e.openView (eval at ur (unknown source), <anonymous>:2899:30)
    at e.module.exports.children.children.events.click (eval at ur (unknown source), <anonymous>:2685:43)
    at t.<anonymous> (<anonymous>:1:8770)
    at t.fireEvent (<anonymous>:3:20039)
    at e.Uc.fireEvent (<anonymous>:4:27311)
    at de (<anonymous>:1:17937)
    at Jc.1 (<anonymous>:4:21559)
    at <anonymous>:2:18566
    at Array.forEach (native)
    at Object.vr [as processCallbacks] (<anonymous>:2:18463)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeVoidFunction(Native Method)
	at com.eclipsesource.v8.V8.executeVoidFunction(SourceFile:1004)
	at com.eclipsesource.v8.V8Object.executeVoidFunction(SourceFile:418)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:599)
	at org.hapjs.render.jsruntime.JsThread.a(SourceFile:49)
	at org.hapjs.render.jsruntime.JsThread$a.handleMessage(SourceFile:188)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by syusikoku** [comment]
import router from '@system.router'
    router.push({uri: uri})
   这种就不会报错

**Comment by charlieysx** [comment]
@syusikoku 这是因为this.$app.$def.router为undefined，直接import可以的话，可能是app.ux里面有问题？

**Comment by syusikoku** [comment]
我直接把你那个文件里面的所有内容都复制过来了。还是报错
我还用npm install 重新初始化过的。运行还是报错。

**Comment by charlieysx** [comment]
this.$app.$def.router.push({ uri: uri })这句在哪个地方调用的？

**Comment by syusikoku** [comment]
在onclick方法中调用的

**Comment by charlieysx** [comment]
额，没看到项目结构代码，看不出是什么问题

**Comment by syusikoku** [comment]
恩没事。我这边用我发的方式可以运行起来。目前就遇到这个问题没有解决。其它的问题都解决了。谢谢你。
